### ISSUE TITLE
Processing entire directories broken

### ISSUE THREAD

**Issue by dwysocki** [astroswego/plotypus#88]
I noticed today that somebody (probably me) broke the feature which allows processing an entire directory of files, by passing the folder as input. This needs to be fixed. The following error was produced on committ 59a7ac1a60890787a1e3435bd7422f69bfd383a1:

```
vstars$ ~/.local/bin/plotypus -i data/ogle-iii/I/ -o out
/usr/lib/python3.5/site-packages/sklearn/utils/fixes.py:64: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead                      
  if 'order' in inspect.getargspec(np.copy)[0]:
Name    A_0     dA_0    Period  Shift   Coverage        Inliers Outliers        R^2 M
SE      MaxDegree       Params                                                      
Traceback (most recent call last):
  File "/home/dwysocki/.local/bin/plotypus", line 9, in <module>
    load_entry_point('plotypus==0.2.6.dev0', 'console_scripts', 'plotypus')()
  File "/home/dwysocki/research/vstars/plotypus/src/plotypus/cli.py", line 423, in main                                                                                  
    processes=args.star_processes, **args_dict)
  File "/home/dwysocki/research/vstars/plotypus/src/plotypus/utils.py", line 102, in pmap                                                                                
    for arg in args:
  File "/home/dwysocki/research/vstars/plotypus/src/plotypus/cli.py", line 389, in <lambda>                                                                              
    else path.join(args.input, filename),
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by dwysocki** [comment]
This has been fixed as of #89.
